apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-hog
  namespace: demo
spec:
  replicas: 20
  selector:
    matchLabels:
      app: cpu-hog
  template:
    metadata:
      labels:
        app: cpu-hog
    spec:
      containers:
        - name: hog
          image: vish/stress
          args:
            - "--cpu"
            - "1"
          resources:
            requests:
              cpu: "200m"
